spring:
  application:
    name: survay-hw-reactive

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

  servlet:
    multipart:
      enabled: true
      resolve-lazily: false
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO