spring:
  application:
    name: survay-hw
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:postgresql://db1:5432/survey_db
    username: survey_user
    password: survey_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      resolve-lazily: false
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    root: INFO